# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(
firstname: 'Emanuel',
lastname: 'Ericsson',
personalnumber: '9202195476',
phonenumber: '0737373123',
avatar: 'avatar1',
address: 'Ormvägen 29',
city: 'Karlstad',
zipcode: '35570',
parentmail: 'lina@filmriket.nu',
access: '1',
email: 'emanuel.ericsson@filmriket.nu',
password: "1585otols",
password_confirmation: "1585otols",
reset_password_token: nil,
reset_password_sent_at: nil,
remember_created_at: nil,
sign_in_count: 1,
current_sign_in_at: "2015-02-06 14:02:10",
last_sign_in_at: "2015-02-06 14:02:10",
current_sign_in_ip: "127.0.0.1",
last_sign_in_ip: "127.0.0.1",
agreement: true,
status: '1',
points: '0'
 )
 
 User.create(
 firstname: 'Erica',
 lastname: 'Emanuelsson',
 personalnumber: '9512213576',
 phonenumber: '0703323923',
 avatar: 'avatar3',
 address: 'Rakvägen 13',
 city: 'Örebro',
 zipcode: '11070',
 parentmail: 'stefan@filmriket.nu',
 access: '1',
 email: 'erica.emanuelsson@filmriket.nu',
 password: "1585otols",
 password_confirmation: "1585otols",
 reset_password_token: nil,
 reset_password_sent_at: nil,
 remember_created_at: nil,
 sign_in_count: 1,
 current_sign_in_at: "2015-02-06 14:02:10",
 last_sign_in_at: "2015-02-06 14:02:10",
 current_sign_in_ip: "127.0.0.1",
 last_sign_in_ip: "127.0.0.1",
 agreement: true,
 status: '1',
 points: '0'
  )
  
  User.create(
  firstname: 'Magnus',
  lastname: 'Liv',
  personalnumber: '9911192456',
  phonenumber: '0739973223',
  avatar: 'avatar5',
  address: 'Genvägen 7B',
  city: 'Risinge',
  zipcode: '25500',
  parentmail: 'ola@filmriket.nu',
  access: '1',
  email: 'magnus.liv@filmriket.nu',
  password: "1585otols",
  password_confirmation: "1585otols",
  reset_password_token: nil,
  reset_password_sent_at: nil,
  remember_created_at: nil,
  sign_in_count: 1,
  current_sign_in_at: "2015-02-06 14:02:10",
  last_sign_in_at: "2015-02-06 14:02:10",
  current_sign_in_ip: "127.0.0.1",
  last_sign_in_ip: "127.0.0.1",
  agreement: true,
  status: '1',
  points: '0'
   )
   
   User.create(
   firstname: 'Edward',
   lastname: 'Karlsson',
   personalnumber: '0105225571',
   phonenumber: '0705738213',
   avatar: 'avatar1',
   address: 'Snigelgatan 104',
   city: 'Kristianstad',
   zipcode: '12350',
   parentmail: 'lucas@filmriket.nu',
   access: '1',
   email: 'edward.karlsson@filmriket.nu',
   password: "1585otols",
   password_confirmation: "1585otols",
   reset_password_token: nil,
   reset_password_sent_at: nil,
   remember_created_at: nil,
   sign_in_count: 1,
   current_sign_in_at: "2015-02-06 14:02:10",
   last_sign_in_at: "2015-02-06 14:02:10",
   current_sign_in_ip: "127.0.0.1",
   last_sign_in_ip: "127.0.0.1",
   agreement: true,
   status: '1',
   points: '0'
    )
    
    User.create(
    firstname: 'Diana',
    lastname: 'Persson',
    personalnumber: '9810213456',
    phonenumber: '073073321',
    avatar: 'avatar4',
    address: 'Baldersgatan 29',
    city: 'Västervik',
    zipcode: '78305',
    parentmail: 'edvin@filmriket.nu',
    access: '1',
    email: 'diana.persson@filmriket.nu',
    password: "1585otols",
    password_confirmation: "1585otols",
    reset_password_token: nil,
    reset_password_sent_at: nil,
    remember_created_at: nil,
    sign_in_count: 1,
    current_sign_in_at: "2015-02-06 14:02:10",
    last_sign_in_at: "2015-02-06 14:02:10",
    current_sign_in_ip: "127.0.0.1",
    last_sign_in_ip: "127.0.0.1",
    agreement: true,
    status: '1',
    points: '0'
     )
     
     User.create(
     firstname: 'Lucas',
     lastname: 'Bengtsson',
     personalnumber: '9602112416',
     phonenumber: '0733473223',
     avatar: 'avatar5',
     address: 'Bohus Norregård',
     city: 'Skruv',
     zipcode: '12005',
     parentmail: 'linus@filmriket.nu',
     access: '1',
     email: 'lucas.bengtsson@filmriket.nu',
     password: "1585otols",
     password_confirmation: "1585otols",
     reset_password_token: nil,
     reset_password_sent_at: nil,
     remember_created_at: nil,
     sign_in_count: 1,
     current_sign_in_at: "2015-02-06 14:02:10",
     last_sign_in_at: "2015-02-06 14:02:10",
     current_sign_in_ip: "127.0.0.1",
     last_sign_in_ip: "127.0.0.1",
     agreement: true,
     status: '1',
     points: '0'
      )
      
      User.create(
      firstname: 'Peter',
      lastname: 'Björk',
      personalnumber: '9612190406',
      phonenumber: '0733412332',
      avatar: 'avatar4',
      address: 'Storgatan 1',
      city: 'Göteborg',
      zipcode: '55570',
      parentmail: 'magnus@filmriket.nu',
      access: '1',
      email: 'peter.bjork@filmriket.nu',
      password: "1585otols",
      password_confirmation: "1585otols",
      reset_password_token: nil,
      reset_password_sent_at: nil,
      remember_created_at: nil,
      sign_in_count: 1,
      current_sign_in_at: "2015-02-06 14:02:10",
      last_sign_in_at: "2015-02-06 14:02:10",
      current_sign_in_ip: "127.0.0.1",
      last_sign_in_ip: "127.0.0.1",
      agreement: true,
      status: '1',
      points: '0'
       )
       
       User.create(
       firstname: 'Elin',
       lastname: 'Johansson',
       personalnumber: '9901010076',
       phonenumber: '0702323223',
       avatar: 'avatar2',
       address: 'Rullstensvägen 2',
       city: 'Hovmantorp',
       zipcode: '70113',
       parentmail: 'roy@filmriket.nu',
       access: '1',
       email: 'elin.johansson@filmriket.nu',
       password: "1585otols",
       password_confirmation: "1585otols",
       reset_password_token: nil,
       reset_password_sent_at: nil,
       remember_created_at: nil,
       sign_in_count: 1,
       current_sign_in_at: "2015-02-06 14:02:10",
       last_sign_in_at: "2015-02-06 14:02:10",
       current_sign_in_ip: "127.0.0.1",
       last_sign_in_ip: "127.0.0.1",
       agreement: true,
       status: '1',
       points: '0'
        )
        
        User.create(
        firstname: 'Johan',
        lastname: 'Carlsson',
        personalnumber: '9202195476',
        phonenumber: '0709988771',
        avatar: 'avatar3',
        address: 'Urvägen 11',
        city: 'Lenhovda',
        zipcode: '10070',
        parentmail: 'jonas@filmriket.nu',
        access: '1',
        email: 'johan.carlsson@filmriket.nu',
        password: "1585otols",
        password_confirmation: "1585otols",
        reset_password_token: nil,
        reset_password_sent_at: nil,
        remember_created_at: nil,
        sign_in_count: 1,
        current_sign_in_at: "2015-02-06 14:02:10",
        last_sign_in_at: "2015-02-06 14:02:10",
        current_sign_in_ip: "127.0.0.1",
        last_sign_in_ip: "127.0.0.1",
        agreement: true,
        status: '1',
        points: '0'
         )
         
         User.create(
         firstname: 'Nils',
         lastname: 'Pettersson',
         personalnumber: '9412295516',
         phonenumber: '0737475123',
         avatar: 'avatar5',
         address: 'Sidgatan 19',
         city: 'Färjestad',
         zipcode: '20345',
         parentmail: 'gota@filmriket.nu',
         access: '1',
         email: 'nils.pettersson@filmriket.nu',
         password: "1585otols",
         password_confirmation: "1585otols",
         reset_password_token: nil,
         reset_password_sent_at: nil,
         remember_created_at: nil,
         sign_in_count: 1,
         current_sign_in_at: "2015-02-06 14:02:10",
         last_sign_in_at: "2015-02-06 14:02:10",
         current_sign_in_ip: "127.0.0.1",
         last_sign_in_ip: "127.0.0.1",
         agreement: true,
         status: '1',
         points: '0'
          )
          User.create(
          firstname: 'Jonas',
          lastname: 'Larsson',
          personalnumber: '9505155575',
          phonenumber: '0705505505',
          avatar: 'avatar3',
          address: 'Deralycke 11',
          city: 'Ormeshaga',
          zipcode: '19033',
          parentmail: 'markus@filmriket.nu',
          access: '1',
          email: 'jonas.larsson@filmriket.nu',
          password: "1585otols",
          password_confirmation: "1585otols",
          reset_password_token: nil,
          reset_password_sent_at: nil,
          remember_created_at: nil,
          sign_in_count: 1,
          current_sign_in_at: "2015-02-06 14:02:10",
          last_sign_in_at: "2015-02-06 14:02:10",
          current_sign_in_ip: "127.0.0.1",
          last_sign_in_ip: "127.0.0.1",
          agreement: true,
          status: '1',
          points: '0'
           )
           User.create(
           firstname: 'Jon',
           lastname: 'Tran',
           personalnumber: '9412193333',
           phonenumber: '0737373130',
           avatar: 'avatar5',
           address: 'Drakvägen 11F',
           city: 'Ronneby',
           zipcode: '36050',
           parentmail: 'abraham@filmriket.nu',
           access: '1',
           email: 'jon.tran@filmriket.nu',
           password: "1585otols",
           password_confirmation: "1585otols",
           reset_password_token: nil,
           reset_password_sent_at: nil,
           remember_created_at: nil,
           sign_in_count: 1,
           current_sign_in_at: "2015-02-06 14:02:10",
           last_sign_in_at: "2015-02-06 14:02:10",
           current_sign_in_ip: "127.0.0.1",
           last_sign_in_ip: "127.0.0.1",
           agreement: true,
           status: '1',
           points: '0'
            )
            User.create(
            firstname: 'Linn',
            lastname: 'Jansson',
            personalnumber: '9903195476',
            phonenumber: '0737372523',
            avatar: 'avatar4',
            address: 'Granvägen 121',
            city: 'Visby',
            zipcode: '90013',
            parentmail: 'jan@filmriket.nu',
            access: '1',
            email: 'linn.jansson@filmriket.nu',
            password: "1585otols",
            password_confirmation: "1585otols",
            reset_password_token: nil,
            reset_password_sent_at: nil,
            remember_created_at: nil,
            sign_in_count: 1,
            current_sign_in_at: "2015-02-06 14:02:10",
            last_sign_in_at: "2015-02-06 14:02:10",
            current_sign_in_ip: "127.0.0.1",
            last_sign_in_ip: "127.0.0.1",
            agreement: true,
            status: '1',
            points: '0'
             )
             User.create(
             firstname: 'Staffan',
             lastname: 'Jonsson',
             personalnumber: '9201195476',
             phonenumber: '0705573155',
             avatar: 'avatar5',
             address: 'Risgatan 3',
             city: 'Malmö',
             zipcode: '10533',
             parentmail: 'karl@filmriket.nu',
             access: '1',
             email: 'staffan.jonsson@filmriket.nu',
             password: "1585otols",
             password_confirmation: "1585otols",
             reset_password_token: nil,
             reset_password_sent_at: nil,
             remember_created_at: nil,
             sign_in_count: 1,
             current_sign_in_at: "2015-02-06 14:02:10",
             last_sign_in_at: "2015-02-06 14:02:10",
             current_sign_in_ip: "127.0.0.1",
             last_sign_in_ip: "127.0.0.1",
             agreement: true,
             status: '1',
             points: '0'
              )
              User.create(
              firstname: 'Rikard',
              lastname: 'Ericsson',
              personalnumber: '9912193336',
              phonenumber: '0707379999',
              avatar: 'avatar3',
              address: 'Kjells gata 12',
              city: 'Moheda',
              zipcode: '15152',
              parentmail: 'olle@filmriket.nu',
              access: '1',
              email: 'rikard.olsson@filmriket.nu',
              password: "1585otols",
              password_confirmation: "1585otols",
              reset_password_token: nil,
              reset_password_sent_at: nil,
              remember_created_at: nil,
              sign_in_count: 1,
              current_sign_in_at: "2015-02-06 14:02:10",
              last_sign_in_at: "2015-02-06 14:02:10",
              current_sign_in_ip: "127.0.0.1",
              last_sign_in_ip: "127.0.0.1",
              agreement: true,
              status: '1',
              points: '0'
               )
               User.create(
               firstname: 'Patrik',
               lastname: 'Renström',
               personalnumber: '0004299877',
               phonenumber: '0737373123',
               avatar: 'avatar1',
               address: 'Storgatan 29',
               city: 'Karlstad',
               zipcode: '35570',
               parentmail: 'morgan@filmriket.nu',
               access: '1',
               email: 'patrik.renstrom@filmriket.nu',
               password: "1585otols",
               password_confirmation: "1585otols",
               reset_password_token: nil,
               reset_password_sent_at: nil,
               remember_created_at: nil,
               sign_in_count: 1,
               current_sign_in_at: "2015-02-06 14:02:10",
               last_sign_in_at: "2015-02-06 14:02:10",
               current_sign_in_ip: "127.0.0.1",
               last_sign_in_ip: "127.0.0.1",
               agreement: true,
               status: '1',
               points: '0'
                )
                User.create(
                firstname: 'Markus',
                lastname: 'Svensson',
                personalnumber: '9112315511',
                phonenumber: '0701103593',
                avatar: 'avatar5',
                address: 'Barrvägen 40B',
                city: 'Ljungby',
                zipcode: '70350',
                parentmail: 'sofie@filmriket.nu',
                access: '1',
                email: 'markus.svensson@filmriket.nu',
                password: "1585otols",
                password_confirmation: "1585otols",
                reset_password_token: nil,
                reset_password_sent_at: nil,
                remember_created_at: nil,
                sign_in_count: 1,
                current_sign_in_at: "2015-02-06 14:02:10",
                last_sign_in_at: "2015-02-06 14:02:10",
                current_sign_in_ip: "127.0.0.1",
                last_sign_in_ip: "127.0.0.1",
                agreement: true,
                status: '1',
                points: '0'
                 )
                 User.create(
                 firstname: 'Niklas',
                 lastname: 'Åberg',
                 personalnumber: '9712192121',
                 phonenumber: '0703636748',
                 avatar: 'avatar2',
                 address: 'Saltön 116',
                 city: 'Osby',
                 zipcode: '50703',
                 parentmail: 'olof@filmriket.nu',
                 access: '1',
                 email: 'niklas.aberg@filmriket.nu',
                 password: "1585otols",
                 password_confirmation: "1585otols",
                 reset_password_token: nil,
                 reset_password_sent_at: nil,
                 remember_created_at: nil,
                 sign_in_count: 1,
                 current_sign_in_at: "2015-02-06 14:02:10",
                 last_sign_in_at: "2015-02-06 14:02:10",
                 current_sign_in_ip: "127.0.0.1",
                 last_sign_in_ip: "127.0.0.1",
                 agreement: true,
                 status: '1',
                 points: '0'
                  )
                  User.create(
                  firstname: 'Jonatan',
                  lastname: 'Svangren',
                  personalnumber: '9504125326',
                  phonenumber: '0737355455',
                  avatar: 'avatar4',
                  address: 'Ormvägen 8',
                  city: 'Tranås',
                  zipcode: '12055',
                  parentmail: 'christoffer@filmriket.nu',
                  access: '1',
                  email: 'jonatan.svangren@filmriket.nu',
                  password: "1585otols",
                  password_confirmation: "1585otols",
                  reset_password_token: nil,
                  reset_password_sent_at: nil,
                  remember_created_at: nil,
                  sign_in_count: 1,
                  current_sign_in_at: "2015-02-06 14:02:10",
                  last_sign_in_at: "2015-02-06 14:02:10",
                  current_sign_in_ip: "127.0.0.1",
                  last_sign_in_ip: "127.0.0.1",
                  agreement: true,
                  status: '1',
                  points: '0'
                   )
                   User.create(
                   firstname: 'Karl',
                   lastname: 'Rönnkvist',
                   personalnumber: '9806113426',
                   phonenumber: '0707171115',
                   avatar: 'avatar2',
                   address: 'Ringvägen 30',
                   city: 'Konga',
                   zipcode: '90431',
                   parentmail: 'alexander@filmriket.nu',
                   access: '1',
                   email: 'karl.ronnkvist@filmriket.nu',
                   password: "1585otols",
                   password_confirmation: "1585otols",
                   reset_password_token: nil,
                   reset_password_sent_at: nil,
                   remember_created_at: nil,
                   sign_in_count: 1,
                   current_sign_in_at: "2015-02-06 14:02:10",
                   last_sign_in_at: "2015-02-06 14:02:10",
                   current_sign_in_ip: "127.0.0.1",
                   last_sign_in_ip: "127.0.0.1",
                   agreement: true,
                   status: '1',
                   points: '0'
                    )

               
                    
                    